import { Translation, Language } from './types';

export const WILAYAS = [
  "Adrar", "Chlef", "Laghouat", "Oum El Bouaghi", "Batna", "Béjaïa", "Biskra", "Béchar", 
  "Blida", "Bouira", "Tamanrasset", "Tébessa", "Tlemcen", "Tiaret", "Tizi Ouzou", "Algiers", 
  "Djelfa", "Jijel", "Sétif", "Saïda", "Skikda", "Sidi Bel Abbès", "Annaba", "Guelma", 
  "Constantine", "Médéa", "Mostaganem", "M'Sila", "Mascara", "Ouargla", "Oran"
];

export const TRANSLATIONS: Record<Language, Translation> = {
  en: {
    searchPlaceholder: "Search for laptops, phones, shoes...",
    trending: "Trending in DZ",
    newArrivals: "New Arrivals",
    price: "Price",
    condition: "Condition",
    store: "Store",
    search: "Search",
    filters: "Filters",
    details: "Product Details",
    buyNow: "Go to Store",
    techPlan: "Project Blueprint",
    monetization: "Monetization",
    architecture: "Architecture",
    language: "Language",
    login: "Login",
    logout: "Logout",
    wilaya: "Wilaya (Location)",
    safetyTip: "Safety Tip: Never pay in advance. Choose 'Cash on Delivery' (Paiement à la livraison).",
    seller: "Seller",
    description: "Description",
    similarItems: "Similar Items",
    callSeller: "Call Seller"
  },
  fr: {
    searchPlaceholder: "Rechercher pc, téléphone, chaussures...",
    trending: "Tendances DZ",
    newArrivals: "Nouvelles Arrivées",
    price: "Prix",
    condition: "État",
    store: "Boutique",
    search: "Rechercher",
    filters: "Filtres",
    details: "Détails du produit",
    buyNow: "Visiter la boutique",
    techPlan: "Plan du Projet",
    monetization: "Monétisation",
    architecture: "Architecture",
    language: "Langue",
    login: "Connexion",
    logout: "Déconnexion",
    wilaya: "Wilaya (Lieu)",
    safetyTip: "Conseil sécurité : Ne payez jamais à l'avance. Choisissez 'Paiement à la livraison'.",
    seller: "Vendeur",
    description: "Description",
    similarItems: "Articles similaires",
    callSeller: "Appeler"
  },
  ar: {
    searchPlaceholder: "ابحث عن لابتوب، هاتف، أحذية...",
    trending: "شائع في الجزائر",
    newArrivals: "وصل حديثاً",
    price: "السعر",
    condition: "الحالة",
    store: "المتجر",
    search: "بحث",
    filters: "تصفية",
    details: "تفاصيل المنتج",
    buyNow: "زيارة المتجر",
    techPlan: "مخطط المشروع",
    monetization: "تحقيق الدخل",
    architecture: "الهندسة",
    language: "اللغة",
    login: "دخول",
    logout: "خروج",
    wilaya: "الولاية",
    safetyTip: "نصيحة أمان: لا تدفع مسبقاً. اختر دائماً 'الدفع عند الاستلام'.",
    seller: "البائع",
    description: "الوصف",
    similarItems: "منتجات مشابهة",
    callSeller: "اتصل بالبائع"
  }
};

export const MOCK_TRENDING_PRODUCTS: any[] = [
  {
    id: 'm1',
    name: 'Samsung Galaxy S23 Ultra',
    price: 180000,
    currency: 'DZD',
    store: 'Ouedkniss',
    condition: 'New',
    imageUrl: 'https://picsum.photos/400/400?random=1',
    category: 'Electronics',
    rating: 4.8,
    location: 'Algiers',
    description: 'Samsung S23 Ultra 256GB, never opened. Warranty 12 months available. Delivery to 58 wilayas.',
    sellerName: 'Amine GSM',
    externalLink: 'https://www.ouedkniss.com'
  },
  {
    id: 'm2',
    name: 'Nike Air Force 1',
    price: 12000,
    currency: 'DZD',
    store: 'Jumia',
    condition: 'New',
    imageUrl: 'https://picsum.photos/400/400?random=2',
    category: 'Fashion',
    rating: 4.5,
    location: 'Oran',
    description: 'Original Nike Air Force 1. Sizes 40-44 available. White color.',
    sellerName: 'Nike Official DZ',
    externalLink: 'https://www.jumia.dz'
  },
  {
    id: 'm3',
    name: 'PlayStation 5 Slim',
    price: 95000,
    currency: 'DZD',
    store: 'Facebook Marketplace',
    condition: 'Used',
    imageUrl: 'https://picsum.photos/400/400?random=3',
    category: 'Gaming',
    rating: 4.2,
    location: 'Blida',
    description: 'PS5 Slim with 2 controllers and FIFA 24. Slightly used, excellent condition.',
    sellerName: 'Karim Games',
    externalLink: 'https://facebook.com'
  },
  {
    id: 'm4',
    name: 'Condor Plume L8 Pro',
    price: 25000,
    currency: 'DZD',
    store: 'Uno',
    condition: 'New',
    imageUrl: 'https://picsum.photos/400/400?random=4',
    category: 'Electronics',
    rating: 3.9,
    location: 'Setif',
    description: 'Condor Plume L8 Pro. Best value for money phone in Algeria.',
    sellerName: 'Uno Hypermarket',
    externalLink: 'https://uno.dz'
  }
];
